wandb_version: 1

learning_rate:
  desc: null
  value: 0.05
learning_rate_decay_every:
  desc: null
  value: 15
learning_rate_decay_rate:
  desc: null
  value: 0.8
learning_rate_decay_start:
  desc: null
  value: 80
optimizer:
  desc: null
  value: adam
_name:
  desc: null
  value: wandb.config
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702418997.432294
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.7.12
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
