# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/145kxtZt2KVhr1jL7nTgH23pXJn5LDnZx
"""

import matplotlib.pyplot as plt

# Data
n_values = [1, 2, 4, 8]
average_data_loading_times = [
    3.835056693946426,
    1.9752402596013297,
    1.217942144502825,
    0.8603327798678826,
]

# Plotting
plt.figure(figsize=(10, 6))
plt.plot(n_values, average_data_loading_times, marker='o')

plt.title('Average Data Loading Time per Epoch vs n')
plt.xlabel('n (Number of Workers)')
plt.ylabel('Average Data Loading Time per Epoch (s)')
plt.grid(True)
plt.xticks(n_values)

plt.show()