wandb_version: 1

learning_rate:
  desc: null
  value: 0.1
learning_rate_decay_every:
  desc: null
  value: 5
learning_rate_decay_rate:
  desc: null
  value: 0.95
learning_rate_decay_start:
  desc: null
  value: 120
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1702438295.269415
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.7.12
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
